/**
 * Scans packages/web/dist/ and generates a TypeScript module that embeds
 * every file via `import ... with { type: "file" }`.  The generated module
 * exports a `WEB_ASSETS` map of { urlPath → embeddedBunfsPath }.
 *
 * Run AFTER the web dashboard has been built (`bun run --filter @orc/web build`).
 * Output: packages/cli/src/_web-manifest.generated.ts
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, posix, relative } from "node:path";

const WEB_DIST = join(import.meta.dir, "..", "..", "web", "dist");
const OUT_FILE = join(import.meta.dir, "..", "src", "_web-manifest.generated.ts");

function walk(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      results.push(...walk(full));
    } else {
      results.push(full);
    }
  }
  return results;
}

const files = walk(WEB_DIST);

const imports: string[] = [];
const entries: string[] = [];

for (let i = 0; i < files.length; i++) {
  const abs = files[i];
  // URL path relative to dist root (e.g. "index.html", "assets/index-xxx.js")
  const urlPath = relative(WEB_DIST, abs).split("\\").join("/");
  // Import path relative to the generated file location (packages/cli/src/)
  const importPath = posix.join("../../web/dist", urlPath);

  imports.push(`import f${i} from ${JSON.stringify(importPath)} with { type: "file" };`);
  entries.push(`  ${JSON.stringify(urlPath)}: f${i},`);
}

const code = `// AUTO-GENERATED by scripts/generate-web-manifest.ts - do not edit
// @ts-nocheck - Bun-specific \`import ... with { type: "file" }\` has no TS declarations
${imports.join("\n")}

/** Map of URL path (relative to web root) → embedded $bunfs path */
export const WEB_ASSETS: Record<string, string> = {
${entries.join("\n")}
};
`;

writeFileSync(OUT_FILE, code, "utf-8");
console.log(`Generated ${OUT_FILE} with ${files.length} embedded assets.`);
